version: '3.9'

services:
  db: 
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    restart: unless-stopped
    ports:
      - "5432:5432"  

  redis:
    image: redis:6.2.5
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    restart: unless-stopped

volumes:
  postgres_data:
